default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - commit

exclude: '.obsidian/.*'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: double-quote-string-fixer
      - id: check-executables-have-shebangs

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args:
          - --config
          - .markdownlint.yaml
          - --fix
        exclude: |
          (?x)^(
              CHANGELOG.md |
              ^.*\.excalidraw.md
          )$
